name: Проверка
on: [push]
jobs:
  linter:
    name: Линтер
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Установка Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.6
    - name: Установка зависимостей
      run: |
        python -m pip install --upgrade pip
        pip install flake8==6.1.0 wemake-python-styleguide==0.18.0 bandit==4.1.1
    - name: Flake8
      run: flake8 .
  tests:
    name: Тесты
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Установка Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.12
    - name: Установка зависимостей
      run: |
        python -m pip install --upgrade pip
        pip install pytest==7.4.2
        pip install numpy
    - name: Pytest
      run: pytest
